import * as LucideIcons from 'lucide-react';

export type IconName = string;
export type IconComponent = LucideIcons.LucideIcon;

export const iconRegistry: Record<string, IconComponent> = {
  account_balance_wallet: LucideIcons.Wallet,
  account_balance: LucideIcons.Landmark,
  add_circle: LucideIcons.CirclePlus,
  admin_panel_settings: LucideIcons.ShieldCheck,
  arrow_back: LucideIcons.ArrowLeft,
  arrow_forward: LucideIcons.ArrowRight,
  arrow_outward: LucideIcons.ArrowUpRight,
  account_tree: LucideIcons.Network,
  call: LucideIcons.Phone,
  campaign: LucideIcons.Megaphone,
  chat: LucideIcons.MessageSquare,
  check: LucideIcons.Check,
  check_circle: LucideIcons.CircleCheckBig,
  child_care: LucideIcons.Baby,
  checklist: LucideIcons.ClipboardCheck,
  content_copy: LucideIcons.Copy,
  chevron_right: LucideIcons.ChevronRight,
  close: LucideIcons.X,
  contact_phone: LucideIcons.PhoneCall,
  dashboard: LucideIcons.LayoutDashboard,
  dashboard_customize: LucideIcons.LayoutGrid,
  description: LucideIcons.FileText,
  accessibility_new: LucideIcons.Accessibility,
  baby_changing_station: LucideIcons.Baby,
  download: LucideIcons.Download,
  draft: LucideIcons.Mail,
  edit_document: LucideIcons.FilePenLine,
  edit_note: LucideIcons.NotebookPen,
  elderly: LucideIcons.PersonStanding,
  edit_square: LucideIcons.SquarePen,
  error: LucideIcons.CircleAlert,
  article: LucideIcons.Newspaper,
  calendar_month: LucideIcons.CalendarDays,
  calendar_today: LucideIcons.CalendarDays,
  construction: LucideIcons.Hammer,
  diamond: LucideIcons.Gem,
  home: LucideIcons.House,
  home_pin: LucideIcons.MapPinned,
  info: LucideIcons.Info,
  open_in_new: LucideIcons.ExternalLink,
  gavel: LucideIcons.Scale,
  event: LucideIcons.CalendarDays,
  event_available: LucideIcons.CalendarCheck,
  expand_more: LucideIcons.ChevronDown,
  face_6: LucideIcons.UserRound,
  family_home: LucideIcons.House,
  family_restroom: LucideIcons.UsersRound,
  format_list_numbered: LucideIcons.ListOrdered,
  grid_view: LucideIcons.Grid2x2,
  group: LucideIcons.Users,
  groups: LucideIcons.Users,
  group_add: LucideIcons.UserRoundPlus,
  health_and_safety: LucideIcons.ShieldPlus,
  hourglass_empty: LucideIcons.Hourglass,
  image: LucideIcons.Image,
  inventory_2: LucideIcons.Package,
  key: LucideIcons.KeyRound,
  location_on: LucideIcons.MapPin,
  lock: LucideIcons.Lock,
  local_hospital: LucideIcons.Hospital,
  location_city: LucideIcons.Building2,
  male: LucideIcons.Mars,
  female: LucideIcons.Venus,
  login: LucideIcons.LogIn,
  logout: LucideIcons.LogOut,
  mail: LucideIcons.Mail,
  map: LucideIcons.Map,
  menu_book: LucideIcons.BookOpen,
  menu: LucideIcons.Menu,
  newspaper: LucideIcons.Newspaper,
  notifications: LucideIcons.Bell,
  pending_actions: LucideIcons.ClipboardList,
  payments: LucideIcons.HandCoins,
  person: LucideIcons.UserRound,
  photo_library: LucideIcons.Images,
  play_arrow: LucideIcons.Play,
  public: LucideIcons.Globe,
  receipt_long: LucideIcons.ReceiptText,
  schedule: LucideIcons.Clock3,
  school: LucideIcons.GraduationCap,
  search: LucideIcons.Search,
  search_off: LucideIcons.SearchX,
  send: LucideIcons.Send,
  share: LucideIcons.Share2,
  settings: LucideIcons.Settings,
  shield: LucideIcons.Shield,
  shield_person: LucideIcons.ShieldCheck,
  star: LucideIcons.Star,
  storefront: LucideIcons.Store,
  straighten: LucideIcons.Ruler,
  support_agent: LucideIcons.Headphones,
  timeline: LucideIcons.ListTree,
  supervised_user_circle: LucideIcons.UserRoundCheck,
  task_alt: LucideIcons.BadgeCheck,
  theater_comedy: LucideIcons.Theater,
  travel_explore: LucideIcons.Compass,
  trending_up: LucideIcons.TrendingUp,
  verified: LucideIcons.BadgeCheck,
  verified_user: LucideIcons.ShieldCheck,
  view_list: LucideIcons.List,
  visibility: LucideIcons.Eye,
  warning: LucideIcons.TriangleAlert,
  bolt: LucideIcons.Zap,
  wrong_location: LucideIcons.MapPinOff,
};

export function resolveIcon(name?: string | null): IconComponent {
  if (!name) return LucideIcons.CircleAlert;
  return iconRegistry[name] ?? LucideIcons.CircleAlert;
}
