/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx,astro}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material You Light Theme
        'surface': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-variant': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#43483d',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'outline': '#74796c',
        'outline-variant': '#c4c8ba',
        'primary': '#486730',
        'on-primary': '#ffffff',
        'primary-container': '#87a96b',
        'on-primary-container': '#213d0b',
        'primary-fixed': '#c9eea9',
        'primary-fixed-dim': '#aed18f',
        'on-primary-fixed': '#0b2000',
        'on-primary-fixed-variant': '#314e1b',
        'secondary': '#9f402d',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd876f',
        'on-secondary-container': '#732010',
        'secondary-fixed': '#ffdad3',
        'secondary-fixed-dim': '#ffb4a5',
        'on-secondary-fixed': '#3e0500',
        'on-secondary-fixed-variant': '#802918',
        'tertiary': '#515f74',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#92a0b7',
        'on-tertiary-container': '#29374a',
        'tertiary-fixed': '#d5e3fc',
        'tertiary-fixed-dim': '#b9c7df',
        'on-tertiary-fixed': '#0d1c2e',
        'on-tertiary-fixed-variant': '#3a485b',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-primary': '#aed18f',
        'surface-tint': '#486730',
      },
      fontFamily: {
        'plus-jakarta': ['Plus Jakarta Sans', 'Inter', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      spacing: {
        'gutter': '20px',
        'container-max': '1200px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
};
