-- Schema dasar Supabase untuk fitur DB dinamis proyek salakanid
-- Tabel yang dicakup:
-- 1. Pengajuan
-- 2. NomorUrut
-- 3. LogKegiatanDukuh

begin;

create table if not exists public."Pengajuan" (
  id bigint generated by default as identity primary key,
  nomor_surat text not null,
  rt_id text not null,
  nama text not null,
  jenis_kelamin text not null,
  tempat_lahir text not null,
  tanggal_lahir text not null,
  status_kawin text not null,
  agama text not null,
  pekerjaan text not null,
  alamat text not null,
  nik text not null,
  keperluan text not null,
  no_hp text not null,
  status text not null default 'menunggu',
  catatan_rt text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pengajuan_nomor_surat_key
  on public."Pengajuan" (nomor_surat);

create index if not exists pengajuan_rt_id_idx
  on public."Pengajuan" (rt_id);

create index if not exists pengajuan_status_idx
  on public."Pengajuan" (status);

create index if not exists pengajuan_created_at_idx
  on public."Pengajuan" (created_at desc);

create index if not exists pengajuan_nik_idx
  on public."Pengajuan" (nik);

create table if not exists public."NomorUrut" (
  id bigint generated by default as identity primary key,
  rt_id text not null,
  tahun integer not null,
  urutan integer not null default 0
);

create unique index if not exists nomor_urut_rt_tahun_key
  on public."NomorUrut" (rt_id, tahun);

create table if not exists public."LogKegiatanDukuh" (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null check (kategori in ('pelayanan', 'administrasi', 'rapat', 'undangan', 'lainnya')),
  tanggal date not null,
  waktu_mulai time,
  waktu_selesai time,
  lokasi text,
  ringkasan text not null,
  hasil_tindak_lanjut text,
  pihak_terlibat text,
  foto_dokumentasi text,
  status_publikasi text not null default 'draft' check (status_publikasi in ('draft', 'publish')),
  urutan_tampil integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists log_kegiatan_status_idx
  on public."LogKegiatanDukuh" (status_publikasi);

create index if not exists log_kegiatan_kategori_idx
  on public."LogKegiatanDukuh" (kategori);

create index if not exists log_kegiatan_tanggal_idx
  on public."LogKegiatanDukuh" (tanggal desc);

create index if not exists log_kegiatan_urutan_idx
  on public."LogKegiatanDukuh" (urutan_tampil desc, tanggal desc);

commit;
